print("Once upon a time there was a princess whose name was Belfar.")
print("She was 19 years of age.")
print("She loved living life to the fullest at 19,")
print("but she despised the name Belfar.")
print("Princess Belfar set out on a mission to change her name")
print("She wanted to choose a name that had meaning,")
print("and represented who she was as a person.")
print("Princess Belfar loves being 19 and her new meaningful name!")
